##### NumPy: Numerical Python
    - Library for numerical and scientific computing
    - It provides support for large, multi-dimensional arrays and matrices, as well as a variety of high-level mathematical functions to operate on these arrays.

In [1]:
import numpy as np 

In [18]:
# Create a NumPy Array
myarr = np.array([3,4,12,35])
print(myarr)
print(type(myarr)) # ndarray: n-dimensional Array

[ 3  4 12 35]
<class 'numpy.ndarray'>


In [19]:
# Inside a numpy Array
def print_info(myarr):
    print("Number of Elements: ", myarr.size) # Total Number of elements in the array
    print("Number of Dimensions: ", myarr.ndim) # number of dimensions
    print("Shape: ",myarr.shape) # Here returns number of elements in each dimension 
                    # In two more dimensional array; it returns # of rows and columns 
    print("Data Type:", myarr.dtype) # Datatype

print_info(myarr) # Calling the function

Number of Elements:  4
Number of Dimensions:  1
Shape:  (4,)
Data Type: int32


In [11]:
print(myarr.dtype) # datatype

myarr1 = np.array([3,4,15,35], dtype = np.int8) # Reducing the required space
print(myarr1)
print(myarr1.dtype)

int32
[ 3  4 15 35]
int8


##### Why NumPy (Numerical Python)?

In [5]:
# Python List Vs NumPy Array
L1 = [5,6,7,9,10]
L2 = [11,6,5,9,8]
print(L1 + L2) # Concatenation not the Addition

# Adding the elements of the Lists
result = []
for a,b in zip(L1,L2):
    result.append(a+b)
print(result)

# Creating ndarrays
marr1 = np.array([1.5, -0.2, 8])
marr2 = np.array([0.5, -4, 3.5])
print("Element wise Addition: ",marr1 + marr2) # Addition

[5, 6, 7, 9, 10, 11, 6, 5, 9, 8]
[16, 12, 12, 18, 18]
Element wise Addition:  [ 2.  -4.2 11.5]


In [9]:
# NumPy array is faster compare to Python List
my_arr = np.arange(1000)
my_list = list(range(1000))

# Computational Time
%timeit my_arr2 = my_arr * 2 # NumPy Array
%timeit my_list2 = [x * 2 for x in my_list] # Python List

1.6 µs ± 13.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
37 µs ± 2.21 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


##### The NumPy ndarray: A Multidimensional Array Object

In [21]:
# Creating ndarrays (1D, 2D & 3D)
arr1D = np.array([3,4,5,6,9])
arr2D = np.array([[5.6, 1.5, 7], [0.5, -4, 3.5]])
arr3D = np.array([[[1.5,2,3], 
                   [4,5,6], 
                   [5,8,7]],
                  [[3,2,1], 
                   [4,5,6],
                   [8,7,9]]])

In [22]:
# Calling the Defined function
print_info(arr1D)
print()
print_info(arr2D)
print()
print_info(arr3D)

Number of Elements:  5
Number of Dimensions:  1
Shape:  (5,)
Data Type: int32

Number of Elements:  6
Number of Dimensions:  2
Shape:  (2, 3)
Data Type: float64

Number of Elements:  18
Number of Dimensions:  3
Shape:  (2, 3, 3)
Data Type: float64


##### Some functions for creating arrays

In [13]:
# Generate arrays of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# Generate (3 X 6)Matrix of zeros
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
# Generate (3 X 5)Matrix of ones
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Create an empty array with 2 elements
np.empty(5) 

array([3.18299369e-313, 4.24399158e-313, 6.36598737e-313, 8.48798317e-313,
       1.06099790e-311])

In [30]:
# Create an empty (2 X 4) Matrix
np.empty((2,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# linspace : Return evenly spaced numbers over a specified interval. 
np.linspace(0,20,10) #linear Space

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [15]:
# eye: Creates identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
# Given a 1D array 
a1 = np.diag([1, 2, 3]) # Returns 2D Array (Matrix) with given vales are diagonal elements
print(a1)

# Given a 2D array 
a2 = np.array([[1, 2], [3, 4]]) 
print(np.diag(a2)) # Returns only the diagonal elements

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 2]
 [3 4]]
[1 4]


In [34]:
# reshape the array into 2 X 5 Matrix 
RS_arr = np.arange(1, 11).reshape(2, 5) 
RS_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

##### Arithmetic with NumPy Arrays
    - Any arithmetic operations between equal-size arrays apply the operation element-wise.

In [36]:
arr1 = np.array([[1, 1.5, 2], [2, 3, 4]])

# Square of each element in arr1
print("Square of each element in arr1 is:", arr1 * arr1) # equal to: arr1**2

# Reciprocal of Each element  in arr1
print("Reciprocal of Each element in arr1 is:", 1/arr1)

arr2 = np.array([[5.6, 1.5, 7], [0.5, -4, 3.5]])
# Comparisons between arrays of the same size yield Boolean arrays
print("Element wise Comparisons: ", arr1 > arr2) # returen Boolean array

print("Element wise Addition: ",arr1 + arr2) # Addition

print("Element wise Multiplecation with scalar: ",5 * arr2) # Scalar Multiplication

Square of each element in arr1 is: [[ 1.    2.25  4.  ]
 [ 4.    9.   16.  ]]
Reciprocal of Each element in arr1 is: [[1.         0.66666667 0.5       ]
 [0.5        0.33333333 0.25      ]]
Element wise Comparisons:  [[False False False]
 [ True  True  True]]
Element wise Addition:  [[ 0.17857143  1.          0.28571429]
 [ 4.         -0.75        1.14285714]]
Element wise Multiplecation with scalar:  [[ 28.    7.5  35. ]
 [  2.5 -20.   17.5]]


##### Indexing and Slicing

In [19]:
arr5 = np.arange(10)*2 # Single Dimensional Array
print(arr5)
print(arr5[5]) # Return value at index 5
print(arr5[2:4]) # Return value at index 2 and 3
print(arr5[::2]) # every second element
print(arr5[arr5>10]) # elemts those are greater than 10
print(arr5[arr5 % 3 == 0]) # select elements those are divisible by 3
print(arr5[(arr5 > 4) & (arr5 < 10)]) # select elements > 4 and < 10

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Two Dimensional Array
print(arr2d[0]) # Return first row elemnts
print(arr2d[0][2]) # Return first row and thrid column

[ 0  2  4  6  8 10 12 14 16 18]
10
[4 6]
[ 0  4  8 12 16]
[12 14 16 18]
[ 0  6 12 18]
[6 8]
[1 2 3]
3


In [17]:
# Fancy Indexing
arr = np.zeros((9, 5))
for x in range(9):
    arr[x]=x
arr    

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8.]])

##### How to get unique items and counts from the array?

In [39]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a) # Return the unique values in your array
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [25]:
# Get the indices of unique values in an array
unique_values, indices_list = np.unique(a, return_index=True)
print(unique_values)
print()
print(indices_list)

[11 12 13 14 15 16 17 18 19 20]

[ 0  2  3  4  5  6  7 12 13 14]


In [41]:
# Get the frequency count of unique values in an array
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(unique_values)
print(occurrence_count)
for a, b in zip(unique_values,occurrence_count):
    print(a,b)

[11 12 13 14 15 16 17 18 19 20]
[3 2 2 2 1 1 1 1 1 1]
11 3
12 2
13 2
14 2
15 1
16 1
17 1
18 1
19 1
20 1


In [29]:
# 2D arrays
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

# Get the unique values
unique_values = np.unique(a_2d) 
print(unique_values); print()

# row wise unique values
unique_rows = np.unique(a_2d, axis=0) 
print(unique_rows); print()

# To get the unique rows, index position, and occurrence count
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows); print()
print(indices); print()
print(occurrence_count); print()

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[0 1 2]

[2 1 1]



##### Basic Statistical Analysis

In [2]:
# Create a NumPy array with your data
data = np.array([10, 15, 15, 20, 25, 30, 35, 40, 45, 50])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Frequency Count
data1 = np.array([1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4])
unique_values, counts = np.unique(data1, return_counts=True)
frequency_dict = dict(zip(unique_values, counts))
print("Frequency count:", frequency_dict)

# Mode
unique, counts = np.unique(data, return_counts=True)
mode = unique[counts.argmax()]
print("Mode:", mode)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

# Range
data_range = np.ptp(data)
print("Range:", data_range)

# Q1 & Q3
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)
print("Q1 is:", q1)
print("Q3 is:", q3)

# IQR
iqr = q3 - q1
print("Interquartile Range (IQR):", iqr)

# Outliers
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr
outliers = [x for x in data if x < lower_bound or x > upper_bound]
print("Outliers:", outliers)

# Min and Max
print("Minimum Valus: ",np.min(data))
print("Maximum Valus: ",np.max(data))

# Correlation 
array1 = np.array([5, 15, 3, 4, 9])
array2 = np.array([12, 30, 41, 25, 16])
correlation = np.corrcoef(array1, array2)
print("Correlation matrix:")
print(correlation)

Mean: 28.5
Median: 27.5
Frequency count: {1: 1, 2: 3, 3: 4, 4: 6}
Mode: 15
Standard Deviation: 13.047988350699889
Variance: 170.25
Range: 40
Q1 is: 16.25
Q3 is: 38.75
Interquartile Range (IQR): 22.5
Outliers: []
Minimum Valus:  10
Maximum Valus:  50
Correlation matrix:
[[ 1.        -0.0697034]
 [-0.0697034  1.       ]]


In [14]:
data = np.array([10, 15, 15, 20, 25, 30, 35, 40, 45, 500,625])
# Outliers
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

# outliers = [x for x in data if x < lower_bound or x > upper_bound]
for x in data:
    if x < lower_bound or x > upper_bound:
        outlier = [x]
        print(outlier)

[500]
[625]


##### Random Number Generation

In [30]:
# Random Numbers (Normal Probability Distribution)
mean = 10
std_dev = 5
num_samples = 10
# num_samples = size=(3, 3)
samples_Nor = np.random.normal(mean, std_dev, num_samples)
print(samples_Nor)

# Standard Normal Distribution
samples_SND = np.random.standard_normal(size=(4, 4))
print(samples_SND)

# Generate an array of 10 random integers between 1 and 100.
random_integer = np.random.randint(1, 101,10)
print("Random integer:", random_integer)

# Generate a random float between 0 and 1
random_float = np.random.random()
print("Random float:", random_float)

# Generate a 3x3 array of random floats between 0 and 1
random_array = np.random.random((3, 3))
print("Random floats array:", random_array)


[ 9.45984243  7.74160371  6.91303188  9.87047206 10.143879   14.50549372
 12.32551279 -1.21954769 12.51467375  9.46543117]
[[ 0.03261194  0.49524247  0.19053512  0.69998333]
 [-0.09229183 -1.27621355  1.2380275   0.23820416]
 [-0.40437341 -1.05047168 -0.72923494  0.19515158]
 [ 1.28893311 -0.76385439 -0.28381893 -0.6389499 ]]
Random integer: [73 69  9 50 12 67 60 11 37 51]
Random float: 0.4936969247509586
Random floats array: [[0.56815782 0.60272131 0.0684117 ]
 [0.93385671 0.73288439 0.46229359]
 [0.68686605 0.3755108  0.27068118]]


In [15]:
# Simulate a coin flip (heads or tails).
coin_flip = np.random.choice(["Heads", "Tails"])
print("Coin flip result:", coin_flip)

# Generate a random integer between 1 and 6 to simulate a die roll
die_roll = np.random.randint(1, 7)
print("Die roll result:", die_roll)

Coin flip result: Tails
Die roll result: 2


##### Basic Mathematics

In [9]:
# Creating Vectors and Matrices
# Create NumPy arrays for vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Create NumPy arrays for matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

#### Unary Universal Functions: 
- Unary universal functions (also known as ufuncs) are NumPy functions that operate element-wise on arrays, producing a new array as output.

In [7]:
arr = np.array([4, 9, 16, 25]) # Given array
sqrt_arr = np.sqrt(arr) # Calculate the square root of each element
print("Square root of the array:", sqrt_arr)

exp_arr = np.exp(arr) # Calculate the exponential of each element
print("Exponential of the array:", exp_arr)

log_arr = np.log(arr) # Calculate the natural logarithm of each element
print("Natural logarithm of the array:", log_arr)

arr = np.array([-3, 5, -7, 10, -1]) # Given array with both positive and negative values
abs_arr = np.abs(arr) # Calculate the absolute value of each element
print("Absolute values of the array:", abs_arr)

arr = np.array([-3, 5, -7, 10, -1])
result = np.square(arr)  # Square each element
print(result)

Square root of the array: [2. 3. 4. 5.]
Exponential of the array: [5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10]
Natural logarithm of the array: [1.38629436 2.19722458 2.77258872 3.21887582]
Absolute values of the array: [ 3  5  7 10  1]
[  9  25  49 100   1]


##### Binary universal functions
- in NumPy are functions that operate on two input arrays and return a single output array.

In [98]:
# Create two arrays
arr1 = np.array([10, 2, 3])
arr2 = np.array([4, 5, 6])

# Add the two arrays element-wise
result = np.add(arr1, arr2)
print("Result of addition:", result)

# Subtract arr2 from arr1 element-wise
result = np.subtract(arr1, arr2)
print("Result of subtraction:", result)

# Multiply the two arrays element-wise
result = np.multiply(arr1, arr2)
print("Result of multiplication:", result)

# Divide arr1 by arr2 element-wise
result = np.divide(arr1, arr2)
print("Result of division:", result)

# Calculate the element-wise maximum between the two arrays
result = np.maximum(arr1, arr2)
print("Element-wise maximum:", result)

Result of addition: [14  7  9]
Result of subtraction: [ 6 -3 -3]
Result of multiplication: [40 10 18]
Result of division: [2.5 0.4 0.5]
Element-wise maximum: [10  5  6]


##### Basic Linear Algebra

In [13]:
vector1 = np.array([10, 2, 3])
vector2 = np.array([4, 5, 6])

# Vector Addition
result_vector = vector1 + vector2

# Vector Subtraction
result_vector = vector1 - vector2

# Scalar Multiplication
scalar = 2
result_vector = scalar * vector1

# Dot Product of Vectors
dot_product = np.dot(vector1, vector2)

matrix1 = np.array([[5, 1], [7, 4]])
matrix2 = np.array([[2, 5], [1, 3]])
# Matrix Multiplication
result_matrix = np.dot(matrix1, matrix2)

# Matrix Transposition
A = np.array([[25, 15], [17, 41]])
transposed = A.T

# Matrix Inversion - inverse of a square matrix
A = np.array([[11, 22], [30, 14]])
inverse = np.linalg.inv(A)

# Eigenvalues and Eigenvectors
A = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


##### Solving Linear Systems of Equations

In [43]:
A = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])

x = np.linalg.solve(A, b)
x

array([1., 2.])

##### Basic Calculus

In [41]:
# Derivative
coefficients = [6, 3, 2, 1]  # Represents f(x) = 6x^3 + 3x^2 + 2x + 1
derivative_coefficients = np.polyder(coefficients)
print(derivative_coefficients)

# Integration
coefficients = [6, 3, 2, 1]  # Represents f(x) = 6x^3 + 3x^2 + 2x + 1
integral_coefficients = np.polyint(coefficients)
print(integral_coefficients)

[18  6  2]
[1.5 1.  1.  1.  0. ]
